### ISSUE TITLE
Separate Nginx and Frontend

### ISSUE THREAD

**Issue by colinlaney** [ledovsky/alice-annotation-tool#3]
Split [Dockerfile](https://github.com/ledovsky/eeg-ic-annotation/blob/23d3f445008821dd1c7ab76bb8475d8ee2b9c6e7/Dockerfile) into separate services.

**Comment by ledovsky** [comment]
Need to clarify, do we really need to split this dockerfile
If we do need, pls specify how to design the new building process

**Comment by colinlaney** [comment]
Let's leave it monolithic.
